import { useState } from 'react';
import { Copy, Check, Share2 } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { usePropertyStore } from '@/hooks/usePropertyStore';
import { calculateNSWStampDuty, calculateMortgage, estimateLMI, calculateBuyingCosts, calculateStampDutyRecovery } from '@/lib/calculations';
import { formatCurrency } from '@/lib/formatters/currency';

export function SummaryExport() {
  const [copied, setCopied] = useState(false);
  const store = usePropertyStore();

  const stampDuty = calculateNSWStampDuty(store.propertyPrice, store.isFirstHomeBuyer);
  const mortgage = calculateMortgage(
    store.propertyPrice,
    store.depositPercent,
    store.interestRate,
    store.loanTermYears,
    store.offsetAmount
  );
  const lmi = estimateLMI(store.propertyPrice, mortgage.loanAmount);
  const depositAmount = store.propertyPrice * (store.depositPercent / 100);
  const costs = calculateBuyingCosts(stampDuty.finalStampDuty, lmi.lmiAmount, depositAmount, store.totalSavings);
  const recovery = calculateStampDutyRecovery(store.propertyPrice, stampDuty.finalStampDuty, store.appreciationRate);

  const generateSummary = () => {
    return `
🏠 SYDNEY PROPERTY CALCULATOR SUMMARY
=====================================

📋 PROPERTY DETAILS
• Property Price: ${formatCurrency(store.propertyPrice)}
• Deposit: ${store.depositPercent}% (${formatCurrency(depositAmount)})
• Total Savings: ${formatCurrency(store.totalSavings)}
• Offset Account: ${formatCurrency(store.offsetAmount)}
• First Home Buyer: ${store.isFirstHomeBuyer ? 'Yes' : 'No'}

💰 LOAN DETAILS
• Loan Amount: ${formatCurrency(mortgage.loanAmount)}
• LVR: ${mortgage.lvr.toFixed(1)}%
• Interest Rate: ${store.interestRate.toFixed(2)}% p.a.
• Loan Term: ${store.loanTermYears} years

📊 REPAYMENTS
• Monthly: ${formatCurrency(mortgage.monthlyRepayment, true)}
• Fortnightly: ${formatCurrency(mortgage.fortnightlyRepayment, true)}
• Total Interest: ${formatCurrency(mortgage.totalInterest)}

🏛️ NSW STAMP DUTY
• Amount: ${formatCurrency(stampDuty.finalStampDuty)}
${store.isFirstHomeBuyer && stampDuty.fhbDiscount > 0 ? `• FHB Discount: ${formatCurrency(stampDuty.fhbDiscount)}` : ''}
• Recovery Time: ${recovery.yearsToRecover.toFixed(1)} years (at ${store.appreciationRate}% growth)

${lmi.lmiRequired ? `🛡️ LMI: ${formatCurrency(lmi.lmiAmount)}` : ''}

💵 TOTAL BUYING COSTS
• Total Funds Required: ${formatCurrency(costs.totalFundsRequired)}
• Remaining After Purchase: ${formatCurrency(costs.remainingAfterPurchase)}

-------------------------------------
Generated by Sydney Property Calculator
    `.trim();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummary());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <Card className="border-slate-200/60 shadow-lg">
      <CardHeader className="pb-3 bg-gradient-to-r from-slate-600 to-slate-700 text-white">
        <CardTitle className="flex items-center gap-2">
          <Share2 className="w-5 h-5" />
          Export Summary
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-6">
        <p className="text-sm text-slate-600 mb-4">
          Copy your calculation summary to clipboard for sharing or records.
        </p>

        <Button
          onClick={handleCopy}
          className="w-full"
          variant={copied ? "secondary" : "default"}
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 mr-2" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4 mr-2" />
              Copy to Clipboard
            </>
          )}
        </Button>

        {/* Preview */}
        <div className="mt-4 p-4 bg-slate-50 rounded-lg max-h-48 overflow-y-auto">
          <pre className="text-xs text-slate-600 whitespace-pre-wrap font-mono">
            {generateSummary()}
          </pre>
        </div>
      </CardContent>
    </Card>
  );
}

