import { useState } from 'react';
import { Copy, Check, Share2 } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { usePropertyStore } from '@/hooks/usePropertyStore';
import { calculateNSWStampDuty, calculateBuyingCosts, calculateMortgage, calculateStampDutyRecovery } from '@/lib/calculations';
import { formatCurrency } from '@/lib/formatters/currency';

export function SummaryExport() {
  const [copied, setCopied] = useState(false);
  const store = usePropertyStore();

  const stampDuty = calculateNSWStampDuty(store.propertyPrice, store.isFirstHomeBuyer);
  const buyingCosts = calculateBuyingCosts(store.propertyPrice, stampDuty.finalStampDuty);
  
  const mortgage = calculateMortgage(
    store.propertyPrice,
    store.availableFunds,
    buyingCosts.totalCosts,
    store.depositAmount,
    store.interestRate,
    store.loanTermYears,
    store.offsetAmount,
    store.householdIncome
  );

  const recovery = calculateStampDutyRecovery(store.propertyPrice, stampDuty.finalStampDuty, 5); // 5% default appreciation

  const generateSummary = () => {
    const isNegativeLoan = mortgage.loanAmount < 0;
    
    return `
🏠 SYDNEY PROPERTY CALCULATOR SUMMARY
=====================================

📋 PROPERTY DETAILS
• Property Price: ${formatCurrency(store.propertyPrice)}
• Available Funds: ${formatCurrency(store.availableFunds)}
• Auto-calculated Deposit: ${formatCurrency(mortgage.autoCalculatedDeposit)}
• Offset Account: ${formatCurrency(store.offsetAmount)}
• First Home Buyer: ${store.isFirstHomeBuyer ? 'Yes' : 'No'}

💰 LOAN DETAILS
${isNegativeLoan 
  ? `• Excess Funds: ${formatCurrency(Math.abs(mortgage.loanAmount))} (No loan needed)`
  : `• Loan Amount: ${formatCurrency(mortgage.loanAmount)}
• LVR: ${mortgage.lvr.toFixed(1)}%`
}
• Interest Rate: ${store.interestRate.toFixed(2)}% p.a.
• Loan Term: ${store.loanTermYears} years
• Deposit %: ${mortgage.depositPercent.toFixed(1)}%

${!isNegativeLoan ? `📊 REPAYMENTS
• Monthly: ${formatCurrency(mortgage.monthlyRepayment, true)}
• Weekly: ${formatCurrency(mortgage.weeklyRepayment, true)}
• % of Household Income: ${mortgage.percentOfIncome.toFixed(1)}%
• Household Income: ${formatCurrency(store.householdIncome)}/month

💸 FIRST YEAR BREAKDOWN
• Interest Paid: ${formatCurrency(mortgage.firstYearInterest)}
• Principal Paid: ${formatCurrency(mortgage.firstYearPrincipal)}
• Total Repayments: ${formatCurrency(mortgage.firstYearInterest + mortgage.firstYearPrincipal)}` : ''}

🏛️ BUYING COSTS
• Stamp Duty: ${formatCurrency(buyingCosts.stampDuty)}
${store.isFirstHomeBuyer && stampDuty.fhbDiscount > 0 ? `• FHB Discount: ${formatCurrency(stampDuty.fhbDiscount)}` : ''}
• Conveyancing: ${formatCurrency(buyingCosts.conveyancing)}
• Building Inspection: ${formatCurrency(buyingCosts.buildingInspection)}
• Loan Establishment: ${formatCurrency(buyingCosts.loanEstablishmentFee)}
• Total Buying Costs: ${formatCurrency(buyingCosts.totalCosts)}

📈 STAMP DUTY RECOVERY
• Recovery Time: ${recovery.yearsToRecover.toFixed(1)} years (at 5% growth)
• Property Value at Recovery: ${formatCurrency(recovery.propertyValueAtRecovery)}

-------------------------------------
Deposit = Available funds - Buying costs
${formatCurrency(store.availableFunds)} - ${formatCurrency(buyingCosts.totalCosts)} = ${formatCurrency(mortgage.autoCalculatedDeposit)}

Generated by Sydney Property Calculator
    `.trim();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummary());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <Card className="border-slate-200/60 shadow-lg">
      <CardHeader className="pb-3 bg-gradient-to-r from-slate-600 to-slate-700 text-white">
        <CardTitle className="flex items-center gap-2">
          <Share2 className="w-5 h-5" />
          Summary Report
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-6">
        <p className="text-sm text-slate-600 mb-4">
          Copy your calculation summary to clipboard for sharing or records.
        </p>

        <Button
          onClick={handleCopy}
          className="w-full"
          variant={copied ? "secondary" : "default"}
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 mr-2" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4 mr-2" />
              Copy to Clipboard
            </>
          )}
        </Button>

        {/* Preview */}
        <div className="mt-4 p-4 bg-slate-50 rounded-lg max-h-48 overflow-y-auto">
          <pre className="text-xs text-slate-600 whitespace-pre-wrap font-mono">
            {generateSummary()}
          </pre>
        </div>
      </CardContent>
    </Card>
  );
}
